### ISSUE TITLE
app_empty shouldn't pull in platformtree yet?

### ISSUE THREAD

**Issue by bgamari** [hackndev/zinc#143]
@farcaller, can we pull platformtree out of `app_empty` for now until we have slightly better coverage of other platforms? I often use `app_empty` to build test my `k20` work and at the moment I get undefined symbols due to lpc17xx references dragged in my `platformtree!`.

Alternatively given that `apps/` is temporary anyways we could just split it into `apps/lpc17xx`, `apps/k20`, etc. This might be a better way forward for the time being.

**Comment by mcoffin** [comment]
A perfect time to do this would be when #288 lands.

I would just make it a part of that PR, but there's an issue with linking when no parts of the zinc crate are actually used (#295).
