### ISSUE TITLE
ioregs!() should not use morestack

### ISSUE THREAD

**Issue by farcaller** [hackndev/zinc#159]
While building https://github.com/hackndev/zinc/pull/136 I've noticed that the test app doesn't build with `-O0` as `__morestack` is undefined for generated ioreg code. There is nothing in ioreg that would need to use stack, I suppose, so `#[no_split_stack]` should be dropped into prologues of generated functions.

Alternatively just wait until freestanding target is WAI.

**Comment by mcoffin** [comment]
Confirmed that this is no longer happening as of e68f861. Closing.
