### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by alexchandel** [hackndev/zinc#161]
RPi is a pretty commonly held ARM board, support would allow lots of others to test zinc.rs. It would mean adding support for the Broadcom SoC that the RPi uses.

**Comment by nistvan86** [comment]
Any chance of moving this forward? Compiling to bare metal Raspberry Pi is definitely possible with Rust (http://blog.thiago.me/raspberry-pi-bare-metal-programming-with-rust/), but without Zinc using plain Cargo it's hard.

Also check out this blog series: http://www.valvers.com/open-software/raspberry-pi/step01-bare-metal-programming-in-cpt1/ and this repository: https://github.com/dwelch67/raspberrypi
I would love to replicate these tutorials in Rust.

**Comment by farcaller** [comment]
I reconsidered my stance that it's out of zinc scope and I'm ok with incoming PRs.
