### ISSUE TITLE
Add cargo support

### ISSUE THREAD

**Issue by bharrisau** [hackndev/zinc#166]
This is to track the steps towards Cargo now that I've had a change to play with it on a branch.

- [X] Refactor folder layout #164 #167 
- [ ] Refactor rake build folder
- [ ] Add separate rake tasks to build non-cargo deps (core, rlib)
- [ ] Refactor linker scripts, have rake copy selected script to build folder
- [ ] Add a zinc config file to specify target
- [ ] Develop target spec and cargo.toml files (waiting on rust-lang/rust#16156)
- [ ] Deploy external example zinc app

**Comment by mcoffin** [comment]
Closed by the landing of #285, a cargo based build system.
