### ISSUE TITLE
Compilation of app_uart fails on strip rust_begin_unwind

### ISSUE THREAD

**Issue by kristofferkoch** [hackndev/zinc#186]
Thanks for making zinc! I find the platform and ideas really exciting, and I'm working on trying to understand how zinc is put together and how to make nice things.

However, when compiling with `rake PLATFORM=lpc17xx build_all`, compilation fails at app_uart with:

```
rustc --opt-level 2 -Z no-landing-pads -g --cfg cfg_mcu_has_spi --cfg mcu_lpc17xx --cfg arch_cortex_m3 --target thumbv7m-linux-eabi -Ctarget-cpu=cortex-m3 -C relocation_model=static  -C lto  --emit obj  -L /home/kko/projects/zinc/build  -o /home/kko/projects/zinc/build/intermediate/uart/app_uart.o  /home/kko/projects/zinc/apps/app_uart.rs 
arm-none-eabi-strip -N rust_stack_exhausted -N rust_begin_unwind -N rust_eh_personality /home/kko/projects/zinc/build/intermediate/uart/app_uart.o
arm-none-eabi-strip: not stripping symbol `rust_begin_unwind' because it is named in a relocation
```

I'm running on debian/unstable with latest rust.

**Comment by mcoffin** [comment]
This isn't really a thing anymore as `fail` was changed to `panic` upstream and some of how the lang items work was changed. Upstream bug was closed.
