### ISSUE TITLE
Let's drop rlibc dep

### ISSUE THREAD

**Issue by farcaller** [hackndev/zinc#235]
Given that rlibc is a bit of a tricky dependency now and the only thing we care is 20 lines of memset/memmove code (and `__aeabi_memset` problem is back) I suggest that we drop rlibc in favor of returning mem\* code back to `support.rs`.

Your opinions?

**Comment by farcaller** [comment]
For the reference, https://github.com/hackndev/zinc/pull/271 moves librlibc into the tree via https://github.com/farcaller/zinc/commit/89ed470118865bdebe147f8b3639f11fa127c027 to make it work.

**Comment by mcoffin** [comment]
For those following the most recent development, the new build system in [mcoffin/new-build](/mcoffin/zinc/tree/new-build) takes librlibc back out of tree by switching to a cargo-based build system.

**Comment by mcoffin** [comment]
This is still a minor PITA and requires [maintenance](https://github.com/mcoffin/rlibc/commit/8cb879f9f8b67444fb9f55db5592c2112147c13e) of a fork of rlibc that defines our libcore as a dependency for any non-standard targets.

**Comment by mcoffin** [comment]
@farcaller now that #400 landed, with the `xargo` build system, the `rlibc` dep isn't that much of a PITA at all.  I think this is likely finally closable if you agree.

In case you weren't tracking it too closely, `xargo` basically lets us use arbitrary dependencies from `crates.io` or wherever without having to worry about propagating that stupid `rust-libcore` dependency upstream.

**Comment by farcaller** [comment]
SGTM.
