### ISSUE TITLE
build_docs failing

### ISSUE THREAD

**Issue by awelkie** [hackndev/zinc#252]
running `rake PLATFORM=lpc17xx build_docs` fails with 

```
error: couldn't find crate 'rlibc' with expected target triple x86_64-unknown-linux-gnu
```

obviously, rustc is looking for the x86_64 version of rlibc, which isn't being built.

**Comment by mcoffin** [comment]
Fixed by #285 and mcoffin/rlibc@ 8cb879f9f8b67444fb9f55db5592c2112147c13e

The command `cargo doc` has replaced the old `build_docs` target from rake.
