### ISSUE TITLE
CMSIS-SVD to ioreg list conversion tool

### ISSUE THREAD

**Issue by aethaniel** [hackndev/zinc#259]
Hi,
I'm totally rookie in Rust and Zinc but I'm really interested in this project for many reasons.
I would like to know if there is a need and/or a plan to convert CMSIS-SVD public files of various Cortex-M devices to a list ioreg macros?
If the SVD format (with or without complementary information like PDSC files) is suitable for such conversion, it could allow some community 'enablement' on lot of different devices.

**Comment by mcoffin** [comment]
Closed by #267 landing?

**Comment by farcaller** [comment]
Yup, thanks for pointing out!
