### ISSUE TITLE
Build fails with errors

### ISSUE THREAD

**Issue by rnestler** [hackndev/zinc#276]
When I tried running
`rake PLATFORM=lpc17xx build_all`
I got some errors: https://gist.github.com/rnestler/ad705dd5542083a77d33#file-first
```
/home/roughl/proggen/projects/zinc/thirdparty/librlibc/src/lib.rs:26:1: 26:11 error: no_std is experimental
/home/roughl/proggen/projects/zinc/thirdparty/librlibc/src/lib.rs:26 #![no_std]
^~~~~~~~~~
/home/roughl/proggen/projects/zinc/thirdparty/librlibc/src/lib.rs:26:1: 26:11 help: add #![feature(no_std)] to the crate attributes to enable
/home/roughl/proggen/projects/zinc/thirdparty/librlibc/src/lib.rs:26 #![no_std]
^~~~~~~~~~ 
```
I could fix that one by using e2261b641d8634ed22688273cb0091c5cca785fa but I'm just getting more errors:
https://gist.github.com/rnestler/ad705dd5542083a77d33#file-second
```
/home/roughl/proggen/projects/zinc/src/ioreg/parser.rs:496:17: 496:22 error: type `syntax::parse::token::InternedString` does not implement any method in scope named `get`
/home/roughl/proggen/projects/zinc/src/ioreg/parser.rs:496           if !s.get().starts_with(prefix) {
                                                                           ^~~~~
```
Am I using a wrong version of rustc?
```
% rustc --version
rustc 1.0.0-nightly (b63cee4a1 2015-02-14 17:01:11 +0000)
```

**Comment by bharrisau** [comment]
Does it build if you remove `.get()`? Looks like `.get()` was recently
replaced with a `Deref` impl.

**Comment by awelkie** [comment]
What version of rustc is Zinc targeting? I haven't been able to get Zinc to build with rust nightlies for a few weeks now.

**Comment by farcaller** [comment]
It is supposed to target nightly, but I think most of us got too frustrated
with rustc breaking every second day. I'm personally taking a timeout until
1.0, prototyping more of the platform tree in ruby now :-)

On Fri, Feb 20, 2015 at 2:16 PM, Allen Welkie <notifications@github.com>
wrote:

> What version of rustc is Zinc targeting? I haven't been able to get Zinc
> to build with rust nightlies for a few weeks now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackndev/zinc/issues/276#issuecomment-75244033>.
>



-- 
Sincerely,
Vladimir "Farcaller" Pouzanov
http://farcaller.net/

**Comment by rnestler** [comment]
@bharrisau 
Removing all the `.get()` worked.
But now I get a
```error: Field target-pointer-width in target specification is required```

**Comment by bharrisau** [comment]
Closing this. See #277
