### ISSUE TITLE
Travis should attempt to build examples for the given platform.

### ISSUE THREAD

**Issue by mcoffin** [hackndev/zinc#289]
Travis currently only builds and tests all the libraries. Linker errors, problems with link scripts, etc are all invisible to travis builds currently. Travis should build the examples for the current platform.

I didn't implement this originally because I"m not that experienced with travis and couldn't think of a good way to have it only build *only* the examples for the **current platform** at the time when I rewrote the travis script for the new build system.

**Comment by farcaller** [comment]
The simplest thing that comes to my mind is to have an env variable specifying the proper example names for each platform.
