### ISSUE TITLE
Jenkins: Concurrent processes fail when updating crates.io index simultaneously

### ISSUE THREAD

**Issue by mcoffin** [hackndev/zinc#313]
Currnetly holding up:
- #298

Example build failure:
- [Jenkins build 31](http://ci.zinc.rs/job/zinc/32/)

**Comment by farcaller** [comment]
One way to fix it is to have dedicated $HOME for each of four workers.

**Comment by mcoffin** [comment]
This isn't really a problem anymore as we've switched to travis (at least for the time being).
