### ISSUE TITLE
Modify examples to be dedicated crates

### ISSUE THREAD

**Issue by farcaller** [hackndev/zinc#331]
As a followup to #330, we need to refactor all the examples to be dedicated crates. This also shows how hard zinc is to use for external users. I'd expect a zinc app to be just one more crate. It is unreasonable to expect the users to download zinc source and add a new "example" entry.

* [x] [blink](https://github.com/farcaller/zinc/commit/23ba2d49d214d4f45e7ae2a14e2280072bab441d) in #318 
* [x] blink_k20
* [x] blink_k20_isr
* [x] blink_lpc17xx
* [x] blink_pt
* [x] blink_stm32f4
* [x] blink_stm32l1
* [x] blink_tiva_c
* [x] bluenrg_stm32l1
* [x] dht22
* [x] empty
* [x] lcd_tiva_c
* [x] uart
* [x] uart_tiva_c
* [x] usart_stm32l1

**Comment by mcoffin** [comment]
Does posborne/zinc-example-lpc17xx not work anymore?

**Comment by farcaller** [comment]
they do. The bundled examples are broken though.

**Comment by mcoffin** [comment]
> It is unreasonable to expect the users to download zinc source and add a new "example" entry.

Ah I was just confused by this sentence.

**Comment by farcaller** [comment]
Right. I forgot about that wiki page when I was writing it.

**Comment by farcaller** [comment]
Landed all in #318.
