### ISSUE TITLE
rustc_front (HIR) fallout

### ISSUE THREAD

**Issue by mcoffin** [hackndev/zinc#342]
I imagine zinc will be effected by fallout similar to what the `syntaxext_lint` crate experienced [here](https://github.com/mcoffin/syntaxext_lint/commit/ef3a8315709801dad5bd0c536153a2c801d4314a)

I already updated the `syntaxext_lint` crate to reflect the changes. Version was bumped to `v0.1.2`.

**Comment by posborne** [comment]
I believe this can be closed.
