### ISSUE TITLE
Where do people from zinc-rs hang out?

### ISSUE THREAD

**Issue by dpc** [hackndev/zinc#366]
IRC? Gitter?

Does this project and people interested in it have any IM room to talk? I'm interested in it.

**Comment by cmr** [comment]
I am too.

**Comment by farcaller** [comment]
I think it's #zinc at irc.mozilla.org (you can find me at #hackndev over at freenode too, but that's not zinc-specific, more like a place where hackndev people hang out).

**Comment by dpc** [comment]
I'd advise to put some official channel in README.md, to gather more people.

**Comment by farcaller** [comment]
Fixed in 411027a4934f60cd620e5be3b5fe513938bcd98a
