### ISSUE TITLE
volatile_cell has undefined behaviour

### ISSUE THREAD

**Issue by huonw** [hackndev/zinc#367]
- it is not legal to mutate data [through a `&` pointer](https://github.com/hackndev/zinc/blob/1112f2e9fb7fb9792e98e0fb5a0cd8da588b2972/volatile_cell/lib.rs#L68) unless that data is contained in [an `UnsafeCell`](http://doc.rust-lang.org/std/cell/struct.UnsafeCell.html)
- the `T` type has no bounds, and so can be used to duplicate arbitrary data, e.g. this prints the same pointer twice:

  ```rust
  fn main() {
      let x = VolatileCell::new(Box::new(1));
      let y: Box<i32> = x.get();
      let z: Box<i32> = x.get();
      println!("{:p} {:p}", y, z);
  }
  ```

  If this is trying to behave like `std::cell::Cell`, this could be fixed by bounding `T: Copy`.

**Comment by farcaller** [comment]
Fixed, thanks for pointing it out.
