### ISSUE TITLE
Doc missing in `hal` module

### ISSUE THREAD

**Issue by gyscos** [hackndev/zinc#373]
Files impacted:

```
hal/tiva_c/sysctl.rs
hal/tiva_c/pin.rs
hal/tiva_c/timer.rs
hal/tiva_c/uart.rs
```

With the `#![deny(missing_docs)]` in `src/lib.rs`, it means tiva_c code cannot compile.

**Comment by mcoffin** [comment]
This was fixed by just just adding `#[allow(missing_docs)]` to the tiva_c modules that were causing the problem in #399 but we should still go back through and actually document things rather than just ignore the errors that we were originally forcing to not ignore.
