### ISSUE TITLE
assembler files

### ISSUE THREAD

**Issue by pftbest** [hackndev/zinc#378]
Hi, can you please tell me how does `src/hal/cortex_m3/sched.S` get compiled using cargo? I can't find any reference to this file in the project. And there seems to be no language feature to include assembly files. I need to have a custom assembly file in my project, but I can't get it to link properly using cargo.

**Comment by mcoffin** [comment]
The scheduler assembly file is currently not built at all. The way forward would be to use the `build.rs` build script to build the assembly and then link against the resulting object file, similar to how one would include regular old C code in a Rust crate.

**Comment by pftbest** [comment]
@mcoffin Thank you.
