### ISSUE TITLE
Add support for Espressif ESP32

### ISSUE THREAD

**Issue by darkdragon-001** [hackndev/zinc#410]
This interest for [Espressiv ESP32](https://en.wikipedia.org/wiki/ESP32) is growing really fast at the moment, especially because of their big functionality on a small footprint for a very low price. 

I would love to see this supported :smiley:

**Comment by farcaller** [comment]
I believe there's no llvm support, thus it's not possible to target the cpu from rust. @whitequark might know more.

Still closing, as it's not something zinc can technically do.

**Comment by whitequark** [comment]
The LLVM backend is reportedly being developed but not by me. I don't know what's its status other than "Espressif is probably paying for it".

**Comment by darkdragon-001** [comment]
Who is developing it? Where can I keep track of the progress?

**Comment by whitequark** [comment]
Some consulting company. I don't think you can.

**Comment by darkdragon-001** [comment]
Thanks for the clarification...

@whitequark I found the [public part of your discussion](https://www.esp32.com/viewtopic.php?t=499) as well as the [official confirmation tweet](https://twitter.com/EspressifSystem/status/824399990965489664).

I also found some files in the [llvm project](https://llvm.org/svn/llvm-project/llvm-gcc-4.2/trunk/gcc/config/xtensa/).

If anybody stumbles over an upgrade regarding this topic, please keep me informed!

**Comment by whitequark** [comment]
> I also found some files in the llvm project.

This is just from a copy of gcc inside llvm. It has no bearing on llvm itself.
