### ISSUE TITLE
Use the same license as the rust project

### ISSUE THREAD

**Issue by afonso360** [hackndev/zinc#414]
Hi,

Would it be possible to relicense this project as Apache 2.0/MIT?
Being Apache only makes it incompatible with a number of common licenses including some of the following

- GNU GPL
- GNU LGPL
- Creative Commons Non-Comercial

A list of commonly use but incompatible licenses can be found [here](https://www.apache.org/legal/resolved.html#category-x).

This would also facilitate with integrating in the rest of the rust ecosystem.
If you completley disagree with this, please close this issue.

Thank you

**Comment by farcaller** [comment]
> Being Apache only makes it incompatible with a number of common licenses including some of the following

That's by design.
