### ISSUE TITLE
Include isr into main zinc rlib

### ISSUE THREAD

**Issue by bharrisau** [hackndev/zinc#45]
There are some issues with symbols going missing on OSX during linking (#41). Investigate and fix.

  - [ ] find source
  - [ ] submit fix
  - [ ] remove symbol stripping from Rakefile

**Comment by mcoffin** [comment]
It turns out that this is due to people using the system `ar` on OS X. autotools now detects the right AR and puts it in `.cargo/config`. Therefore, this was fixed with the landing of #285.
