### ISSUE TITLE
app_blink binary size increased by 6 bytes

### ISSUE THREAD

**Issue by farcaller** [hackndev/zinc#78]
674df0d0142c9387fd409e2a30d2690d95bf051a increased binary size by 6+2 padding bytes, which is quite strange given there is no change in application logic.

**Comment by mcoffin** [comment]
@farcaller Isn't [this](https://github.com/hackndev/zinc/commit/674df0d0142c9387fd409e2a30d2690d95bf051a#diff-838e81e701d5e83238783b0b40efb3a5R74) a runtime check that was added that likely caused the size increase?

**Comment by farcaller** [comment]
Makes sense.
